#! /usr/bin/env python3

import sys
import math

bin=float(sys.argv[1])
if bin==1.0:
        for l in sys.stdin:
                print(l.strip())
else:
        for l in sys.stdin:
	        l=map(float,l.strip().split(","))
	        l=map(lambda x:max(x,0.0),l)
	        l=map(lambda x:int(math.ceil( x/bin)) , l)
	        l=map(str,l)
	        print(",".join(l))
