#! /usr/bin/env python3
import sys


legend={
    "Bases size": ["SC","RL", "IN", "FN", "BA" ,"FC" ,"DL" ,"BS" ,"TL" ,"FP"],
    "Mapping data": ["BF", "AP" ,"MQ"] ,
    "Quality size": ["QS"],
    "Read Names":["RN"] ,
    "Flow Signal": ["ZMB"]
}
invertedLegend={}
for type,blocks in legend.items():
    for b in blocks:
        invertedLegend[b]=type

sizes={}  
sys.stdin.readline()
for l in sys.stdin:
    l=l[l.index(" size")+5:].strip()
    size=int(l[:l.index(" ")])
    blockName=l[l.rindex(" "):].strip()
    type="AUX size"
    if blockName in invertedLegend:
        type=invertedLegend[blockName]
    
    if type not in sizes:
        sizes[type]=0
    sizes[type]+=size


for type,size in sizes.items():
    sys.stderr.write("%s= %d\n"%(type,size/(1024)))
