#! /usr/bin/env python3
import sys

begin=int(sys.argv[1].split(":")[1].split("-")[0])
l=sys.stdin.readline()

while l!="":
    ll=l.split("\t")
    if int(ll[3])>begin:
        print(l.strip())
    l=sys.stdin.readline()

    
for l in sys.stdin:
    print(l.strip())
